Keycard initial instegration
status-im/status-lib pull request #63
Opened 2021-09-28 10:08 UTC by gravityblast

Initial integration of Keycard using the nim/go wrapper https://github.com/status-im/nim-keycard-go.

The only command implemented in status-lib now is the `select` command. 
If everything works in desktop, we can start implementing here all the commands already implemented in the wrapper.

2021-09-30 16:49 UTC, michaelsbradleyjr requested changes, later dismissed
Tests workflow is failing in macOS because `install_name_tool` needs to be used on `libkeycard.dylib` like we do for `libstatus.dylib`:

https://github.com/status-im/status-lib/blob/keycard/nim_status_lib.nimble#L47-L49

Test workflow is failing in Linux due to, I think, a missing package:

https://github.com/status-im/status-lib/pull/63/checks?check_run_id=3756546833#step:8:86

```
# pkg-config --cflags  -- libpcsclite
Package libpcsclite was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcsclite.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libpcsclite' found
pkg-config: exit status 1
```

Maybe  it's something we can install at the start of the workflow with `apt`?

https://packages.ubuntu.com/focal/libpcsclite-dev

2021-09-30 16:49 UTC, michaelsbradleyjr commented on Makefile
> +	LD_LIBRARY_PATH_NIMBLE := $(STATUSGO_LIBDIR):$(KEYCARDGO_LIBDIR):$(LD_LIBRARY_PATH_NIMBLE)
My understanding is that it's best to not use tabs in non-recipe sections of a Makefile, though that understanding could be outdated or I misunderstood the guidance re: when to use and not use tabs.

2021-09-30 16:49 UTC, michaelsbradleyjr commented on Makefile
> +	PATH_NIMBLE := $(STATUSGO_LIBDIR):$(KEYCARDGO_LIBDIR):$(PATH_NIMBLE)
See my previous comment re: tabs in non-recipe sections of a Makefile.

2021-09-30 18:08 UTC, michaelsbradleyjr commented
I added several commits re: the changes I requested. The GHA tests workflow is now passing on all platforms.

2021-09-30 19:36 UTC, michaelsbradleyjr commented
I've just rebased this PR branch against current `master`.

2021-10-01 09:24 UTC, gravityblast commented
thank you @michaelsbradleyjr , I also added a new commit and then this PR should be ready to be reviewed/merged

2021-10-01 13:46 UTC, iurimatias commented on status/types/keycard.nim
> +
types should be moved to the root ./types/keycard.nim

2021-10-01 14:35 UTC, gravityblast commented
@iurimatias I moved the types and from the statusgo backend I catch the exception and re-raise it

2021-10-04 21:21 UTC, merged